license="All Rights Reserved"
[[mods]]
modId="worldgen_assist"
version="0.1.0-alpha.4+mc26.3"
displayName="Worldgen Assist"
description='''Experimental client-assisted world generation.'''
[[mixins]]
config="worldgen_assist.mixins.json"
[[dependencies.worldgen_assist]]
modId="neoforge"
type="required"
versionRange="[26.3.0.13-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.worldgen_assist]]
modId="minecraft"
type="required"
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"
