[CmdletBinding()]
param([switch]$Execute,[Parameter(Mandatory)][string]$GateRoot,[string]$ReuseRawRoot)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$workspace=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$base=Join-Path $workspace 'test-artifacts';$parentPath=(Resolve-Path -LiteralPath $GateRoot).Path
if(-not $parentPath.StartsWith($base+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Owned failed gameplay child required'}
$reusePath=if($ReuseRawRoot){(Resolve-Path -LiteralPath $ReuseRawRoot).Path}else{$null};if($reusePath -and -not $reusePath.StartsWith($base+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Owned failed raw-copy child required'}
if(-not $Execute){@{parent=$parentPath;reused_raw_root=$reusePath;scope='One stopped original B-center region, actual3461 targeted receipt scope, stock codec/heightmap/collision/dry-floor diagnosis';new_games=0;new_junit=0;mod_builds=0;remote_root='E:/WorldgenAssist/port26.3'}|ConvertTo-Json;exit 0}
$root=Join-Path $base ('gameplay-site-diagnosis-'+(Get-Date -Format 'yyyyMMdd-HHmmss-fff'));New-Item -ItemType Directory -Path $root|Out-Null
$issues=[Collections.Generic.List[string]]::new();$steps=[Collections.Generic.List[object]]::new();$inventory=@();$classpathInventory=@();$report=$null;$lock=$null;$before=@();$jar=$null;$sha=$null
. (Join-Path $PSScriptRoot 'WorldgenMeasurementRegion.ps1')
function Manifest {$files=@();foreach($n in @('src','loaders/forge/src','loaders/neoforge/src','scripts')){$files+=Get-ChildItem -LiteralPath (Join-Path $workspace $n) -Recurse -File};foreach($n in @('gradle.properties','build.gradle','settings.gradle','loaders/forge/build.gradle','loaders/neoforge/build.gradle')){$files+=Get-Item -LiteralPath (Join-Path $workspace $n)};@($files|Sort-Object FullName|ForEach-Object {(Get-FileHash -LiteralPath $_.FullName).Hash+'  '+$_.FullName.Substring($workspace.Length+1).Replace('\','/')})}
function Step([string]$Name,[string]$Executable,[string[]]$Arguments,[int]$Seconds=120){$info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$Executable;$info.WorkingDirectory=$workspace;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true;foreach($a in $Arguments){[void]$info.ArgumentList.Add($a)};$p=[Diagnostics.Process]::new();$p.StartInfo=$info;try{if(-not $p.Start()){throw 'Cannot start offline step'};$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync();$done=$p.WaitForExit($Seconds*1000);if(-not $done){$p.Kill($true);$p.WaitForExit()};[IO.File]::WriteAllText((Join-Path $root "$Name-out.log"),$o.GetAwaiter().GetResult());[IO.File]::WriteAllText((Join-Path $root "$Name-err.log"),$e.GetAwaiter().GetResult());$steps.Add(@{name=$Name;success=($done -and $p.ExitCode -eq 0);exit_code=$p.ExitCode;timed_out=(-not $done)});Write-Host "GAMEPLAY_SITE_STEP name=$Name success=$($steps[-1].success)";if(-not $steps[-1].success){throw "Step failed: $Name"}}finally{$p.Dispose()}}
function Inventory([string]$Name,[string]$World){
    if($World -notmatch '^scenario-overworld-vanilla-p2-performance-[0-9-]+$'){throw 'Exact original world required'}
    $code='$ErrorActionPreference="Stop";$env:TEMP="E:/WorldgenAssist/temp";$env:TMP=$env:TEMP;if(@(Get-CimInstance Win32_Process -Filter "Name=''java.exe''"|Where-Object {$_.CommandLine -and $_.CommandLine.Replace(''\'',''/'') -match ''E:/WorldgenAssist/port26.3/fabric-server-launch.jar''}).Count){throw "Owned server live"};$p=''E:/WorldgenAssist/port26.3/'+$World+'/dimensions/minecraft/overworld/region/r.-48.78.mca'';$f=Get-Item -LiteralPath $p;if($f.Length -gt 128MB){throw "Region bound"};[ordered]@{path=$p;bytes=$f.Length;sha256=(Get-FileHash -LiteralPath $p).Hash}|ConvertTo-Json'
    $encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($code));Step $Name (Get-Command ssh.exe).Source @('-o','BatchMode=yes','-o','ConnectTimeout=15','gen1c@100.103.102.109','powershell -NoProfile -NonInteractive -EncodedCommand '+$encoded) 60
    return (Get-Content -LiteralPath (Join-Path $root "$Name-out.log") -Raw|ConvertFrom-Json)
}
try {
    $lock=[IO.File]::Open((Join-Path $base 'validation-matrix.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)
    $parent=Get-Content -LiteralPath (Join-Path $parentPath 'summary.json') -Raw|ConvertFrom-Json;$case=Join-Path $parentPath 'original';$result=Get-Content -LiteralPath (Join-Path $case 'scenario-result.json') -Raw|ConvertFrom-Json;$remote=Get-Content -LiteralPath (Join-Path $case 'remote-evidence/remote-result.json') -Raw|ConvertFrom-Json;$scan=Get-Content -LiteralPath (Join-Path $case 'clients/owner-1/client/gameplay-probe/result-scan.json') -Raw|ConvertFrom-Json
    if($parent.schema -ne 'worldgen-assist.ordinary-gameplay-gate.v1' -or $parent.success -or $parent.steps.Count -ne 5 -or @($parent.steps[0..3]|Where-Object {-not $_.success -or $_.exit_code -or $_.timed_out}).Count -or $parent.steps[4].name -ne 'runtime-original' -or $parent.steps[4].success -or $result.success -or -not $result.cleanup_safe -or -not $remote.cleanup_safe -or $result.failure -notmatch 'ScenarioOwnerB / scan / .*no bounded natural dry' -or $scan.success -or $scan.visited_columns -ne 16641 -or $scan.natural_floor_columns -ne 0 -or $scan.health -ne 20 -or -not $scan.alive -or -not $scan.flying -or $scan.position[1] -ne 150 -or $result.performance.measured.Count -ne 1 -or $result.performance.measured[0].completed_tasks -ne 10658 -or $result.performance.measured[0].failed_tasks -or $result.performance.measured[0].timeouts){throw 'Exact closed B64 selector failure required'}
    $old=[IO.File]::ReadAllLines((Join-Path $parentPath 'source-manifest-before.sha256'));if(($old-join "`n") -cne ([IO.File]::ReadAllLines((Join-Path $parentPath 'source-manifest-after.sha256'))-join "`n")){throw 'Original source changed'};$before=Manifest;$added=@('scripts/GameplaySiteInspector263.java','scripts/Run-GameplaySiteDiagnosis.ps1')
    if(($old-join "`n") -cne (@($before|Where-Object {$_.Substring(66) -notin $added})-join "`n")){throw 'Only two offline diagnostic additions permitted'};[IO.File]::WriteAllLines((Join-Path $root 'source-manifest-before.sha256'),$before)
    $a=@($parent.artifacts|Where-Object loader -eq 'fabric');if($a.Count -ne 1 -or $a[0].version -ne '0.1.0-alpha.8-dev.23+mc26.3' -or (Get-FileHash -LiteralPath $a[0].path).Hash -ne $a[0].sha256){throw 'Exact production23 JAR required'};$jar=$a[0].path;$sha=$a[0].sha256
    $classpathInventory=@(Get-Content -LiteralPath (Join-Path $case 'clients/owner-0/installed-client-classpath.json') -Raw|ConvertFrom-Json);foreach($entry in $classpathInventory){if((Get-FileHash -LiteralPath $entry.path).Hash -ne $entry.sha256){throw 'Original runtime changed'}};$mc=@($classpathInventory|Where-Object name -eq 'original Minecraft 26.3 client');if($mc.Count -ne 1 -or $mc[0].sha256 -ne '4508D006323F24FA02876310C192D739AF56516EB259000AC50F0909A68C9A2D'){throw 'Exact original game required'}
    $classpath=(@($classpathInventory.path)+@($jar))-join ';';$classes=Join-Path $root 'classes';New-Item -ItemType Directory -Path $classes|Out-Null;Copy-Item -LiteralPath $PSCommandPath,(Join-Path $PSScriptRoot 'GameplaySiteInspector263.java') -Destination $root
    $jdk='C:/Program Files/Java/jdk-25.0.4/bin';Step 'compile-one-offline-reader' (Join-Path $jdk 'javac.exe') @('-encoding','UTF-8','-proc:none','-cp',$classpath,'-d',$classes,(Join-Path $PSScriptRoot 'GameplaySiteInspector263.java'))
    if($reusePath){
        $reuse=Get-Content -LiteralPath (Join-Path $reusePath 'summary.json') -Raw|ConvertFrom-Json
        if($reuse.schema -ne 'worldgen-assist.gameplay-site-diagnosis.v1' -or $reuse.success -or $reuse.parent -ne $parentPath -or $reuse.steps.Count -ne 4 -or ($reuse.steps.name-join ';') -cne 'compile-one-offline-reader;region-before;copy-one-stopped-region;region-after' -or @($reuse.steps|Where-Object {-not $_.success -or $_.exit_code -or $_.timed_out}).Count -or $reuse.issues.Count -ne 1 -or $reuse.issues[0] -notmatch 'Exact actual B receipt coordinates required' -or $null -ne $reuse.site){throw 'Exact pre-inspection receipt assertion failure required'}
        $reuseBefore=[IO.File]::ReadAllLines((Join-Path $reusePath 'source-manifest-before.sha256'));if(($reuseBefore-join "`n") -cne ([IO.File]::ReadAllLines((Join-Path $reusePath 'source-manifest-after.sha256'))-join "`n") -or (@($reuseBefore|Where-Object {$_.Substring(66) -notin $added})-join "`n") -cne (@($before|Where-Object {$_.Substring(66) -notin $added})-join "`n")){throw 'Only exact diagnostic-source corrections may differ'}
        $inventory=$reuse.inventory;$local=Join-Path $reusePath 'r.-48.78.mca';if($inventory.path -ne ('E:/WorldgenAssist/port26.3/'+$remote.case+'/dimensions/minecraft/overworld/region/r.-48.78.mca')){throw 'Retained source region differs'}
        foreach($name in @('region-before','region-after')){$row=Get-Content -LiteralPath (Join-Path $reusePath ($name+'-out.log')) -Raw|ConvertFrom-Json;if(($row|ConvertTo-Json -Compress) -cne ($inventory|ConvertTo-Json -Compress)){throw 'Retained before/after source hash differs'}}
    }else{
        $inventory=Inventory 'region-before' $remote.case;$local=Join-Path $root 'r.-48.78.mca';Step 'copy-one-stopped-region' (Get-Command scp.exe).Source @('-q',('gen1c@100.103.102.109:'+$inventory.path),$local) 60
        $afterRemote=Inventory 'region-after' $remote.case;if(($inventory|ConvertTo-Json -Compress) -cne ($afterRemote|ConvertTo-Json -Compress)){throw 'Remote region changed'}
    }
    if((Get-Item -LiteralPath $local).Length -ne $inventory.bytes -or (Get-FileHash -LiteralPath $local).Hash -ne $inventory.sha256){throw 'Immutable local region copy differs'}
    $clientLog=Get-Content -LiteralPath (Join-Path $case 'clients/owner-1/client/logs/latest.log') -Raw;$allReceived=@([regex]::Matches($clientLog,'benchmark\.chunk_received repeat=1 chunk=(-?\d+,-?\d+)\b')|ForEach-Object {$_.Groups[1].Value}|Sort-Object -Unique)
    $expected=@{};foreach($offset in @(Get-WorldgenMeasurementOffsets 32 'view')){$expected[([string](-1512+$offset.x)+','+([string](2512+$offset.z)))]=$true};$received=@($allReceived|Where-Object {$expected.ContainsKey($_)});if($expected.Count -ne 3461 -or $received.Count -ne 3461){throw 'Exact targeted actual B receipt coverage required'}
    $descriptor=Join-Path $root 'descriptor.json';@{region=$local;reader_copy=(Join-Path $root 'reader-copy/r.-48.78.mca');output=(Join-Path $root 'site.json');received=$received}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $descriptor -Encoding utf8
    Step 'read-original-saved-site' (Join-Path $jdk 'java.exe') @('-Xmx1g','-cp',($classes+';'+$classpath),'io.github.genichimaruo.worldgenassist.server.GameplaySiteInspector263',$descriptor) 300;$report=Get-Content -LiteralPath (Join-Path $root 'site.json') -Raw|ConvertFrom-Json
    if(-not $report.success){throw 'Site diagnosis incomplete'}
}catch{$issues.Add($_.Exception.ToString())}
finally {
    try {$after=Manifest;[IO.File]::WriteAllLines((Join-Path $root 'source-manifest-after.sha256'),$after);if($before.Count -and ($before-join "`n") -cne ($after-join "`n")){$issues.Add('Source changed')};if($sha -and (Get-FileHash -LiteralPath $jar).Hash -ne $sha){$issues.Add('Product JAR changed')};$raw=if($reusePath){Join-Path $reusePath 'r.-48.78.mca'}else{Join-Path $root 'r.-48.78.mca'};if($inventory -and (Test-Path -LiteralPath $raw) -and (Get-FileHash -LiteralPath $raw).Hash -ne $inventory.sha256){$issues.Add('Immutable copied region changed')};foreach($entry in $classpathInventory){if((Get-FileHash -LiteralPath $entry.path).Hash -ne $entry.sha256){$issues.Add('Runtime changed')}};if(Test-Path -LiteralPath (Join-Path $root 'site.json')){$report=Get-Content -LiteralPath (Join-Path $root 'site.json') -Raw|ConvertFrom-Json}}catch{$issues.Add($_.Exception.ToString())};if($lock){$lock.Dispose()}
    @{schema='worldgen-assist.gameplay-site-diagnosis.v1';success=($issues.Count -eq 0);root=$root;parent=$parentPath;steps=@($steps);inventory=$inventory;site=$report;issues=@($issues);new_games=0;new_junit=0;mod_builds=0;scope='Exact closed B64-selector failure; one stopped original region with actual client receipt scope. Original stored heightmap/paletted codec/collision diagnosis, no saved-world repair or safety/beta verdict.'}|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $root 'summary.json');Write-Output "GAMEPLAY_SITE_DIAGNOSIS success=$($issues.Count -eq 0) summary=$(Join-Path $root 'summary.json')"
}
if($issues.Count){exit 1}
